export const printTheme = {
  colors: {
    canvas: "#F8FAF7",
    ink: "#10201A",
    surface: "#FFFFFF",
    primary: "#157A6E",
    line: "#DFE9E2",
    soft: "#EEF5F1",
    muted: "#748179",
  },
  fontSizes: {
    reportTitle: 34,
    title: 25,
    section: 23,
    song: 19,
    summary: 18,
    member: 17,
    metadata: 15,
    body: 14,
    footer: 11,
  },
  fontFamily: "Arial, Helvetica, sans-serif",
  fontWeights: {
    regular: 400,
    black: 900,
  },
  lineHeights: {
    title: 1.15,
    heading: 1.2,
    summary: 1.35,
  },
  layout: {
    pageMargin: "18mm",
    pageMaxWidth: "820px",
    footerBottom: "10mm",
  },
  radii: {
    summary: 22,
    song: 18,
  },
  spacing: {
    page: "34px 28px 42px",
    title: "10px 0 24px",
    summary: 24,
    summaryBottom: 28,
    section: "28px 0 14px",
    sectionBottom: 10,
    song: "16px 18px",
    songTitleBottom: 8,
    songBottom: 14,
    memberBottom: 12,
    memberStatusTop: 3,
  },
} as const;
